### PR TITLE
support pytest 5.0.0+ exit codes

### LINKED ISSUE #196: Python tests not working with pytest 5.0.0
The constant `_pytest.main.EXIT_TESTSFAILED` is no longer available in pytest 5.0.

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Pytest moved their exit code to an Enum class named ExitCode in 5.0.0 and up: https://github.com/pytest-dev/pytest/commit/2b92fee1c315469c3f257673a508e51a1f1a6230#diff-7191acb1a6aaab2f77b6e53ce837e348

Without this change, colcon fails to run pytests with the following error:
```
[4.875s] ERROR:colcon.colcon_core.task.python.test:Exception in Python testing step extension 'pytest': cannot import name 'EXIT_TESTSFAILED'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/task/python/test/__init__.py", line 75, in test
    return await extension.step(self.context, env, setup_py_data)
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/task/python/test/pytest.py", line 157, in step
    from _pytest.main import EXIT_TESTSFAILED
ImportError: cannot import name 'EXIT_TESTSFAILED'
```

Edit: AFAICT test failures appear unrelated to this change and are present on [master cron jobs](https://travis-ci.org/colcon/colcon-core/jobs/552574282)

Fixes #196.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the patch.

Can you please invert the `try` / `except` logic so that the `try` block contains the code used moving forward and the `except` block contains the fallback code for earlier `pytest` versions.

**Comment by dirk-thomas** [comment]
> AFAICT test failures appear unrelated to this change and are present on master cron jobs

Actually the failing cron jobs for master are all due to the `pytest` 5.0 release. Since this needs additional fixes I have created #200 which includes the changes from this PR. Therefore I will close this as a duplicate.

Anyway thank you for creating the patch.

**Comment by mikaelarguedas** [comment]
Sounds good, glad it helped getting the compatibility fix in
